# Purpose: To specify selectivity parameterizations for the fishery and the survey
# Creator: Matthew LH. Cheng
# Date: 10/30/22


#'
#' @param Fish_Funct_Form Functional form for Fishery Selectivity - Options are Asmyp and Dome
#' @param Surv_Funct_Form Functional form for Survey Selectivity - Default is Asymptotic
#' @param ages ages we have in our assessment
#' @param Fish_Time Whether we want time-varying selex or not - Options are constant and 2DAR1 - 2DAR1 is very preliminary
#' @param a50_fish A50 parameter for logistic selectivity for fishery 
#' @param k_fish Slope paramter for logistic selectivity for fishery
#' @param amax_fish Age at max selection for selectivity in dome-shaped fishery selex
#' @param delta_fish Slope parameter for selectivity in dome-shaped fishery selex
#' @param a50_surv A50 parameter for logistic selectivity for survey 
#' @param k_surv Slope parameter for logistic selectivity for survey 
#' @param Sigma_Fish Variance parameter for Time varying processes
#' @param rho_age_fish Correlation parameter for age varying fishery selex processes
#' @param rho_time_fish Correlation parameter for time varying fishery selex processes


specify_selex <- function(Fish_Funct_Form, Surv_Funct_Form = "Asymp", ages, 
                          Fish_Time, a50_fish, k_fish, amax_fish, delta_fish,
                          a50_surv, k_surv, Sigma_Fish, rho_age_fish, rho_time_fish) {
  
  require(mvtnorm) # For multivariate draws
  
  if(Fish_Time %in% c("2DAR1", "1DAR1_a", "1DAR1_y")) {
    
    # Create an array to store deviation parameters in if we are specifying time varying stuff
    Selex_dev <- array(dim = c(n_years, length(ages), n_sims),
                       dimnames = list( # Set up dimensions names
                         c(paste("Year", 1:n_years, sep = "_")), # Years 
                         c(paste("Age", ages, sep = "_")), # Ages 
                         c(paste("Sim",1:n_sims)) # Simulation 
                       ))
    
  } # if statement to create a selectivity array
  
# Fishery -----------------------------------------------------------------

  ### Asymptotic Selex --------------------------------------------------------------

  if(Fish_Funct_Form == "Asymp") {
    
    # Base functional form here - scale to a max of 1
    Fish_Selex <- 1 / (1 + exp(-1 * (ages - a50_fish) / k_fish)) / max( 1 / (1 + exp(-1 * (ages - a50_fish) / k_fish)) )
                         
  } # if functional form is asymptotic
  
  
  ### Dome Shaped Selex -------------------------------------------------------

  
  if(Fish_Funct_Form == "Dome") {
    
    # Base Fucntional Form here - use Punt et al. 1994 parameterization (amax and delta)
    p_fish <- (0.5 * (sqrt(amax_fish^2 + 4*delta_fish^2) - amax_fish)) # Derive power parameter here first
    
    # Now calculate Selex for dome-shaped - scale to a max of 1
    Fish_Selex <- (ages/amax_fish) ^ (amax_fish/p_fish) * exp((amax_fish - ages) / p_fish) / max( (ages/amax_fish) ^ (amax_fish/p_fish) * exp((amax_fish - ages) / p_fish) )
    
  } # if functional form is dome-shaped
  

# Constant Selex for the Fishery ----------------------------------------------------------
  
  if(Fish_Time == "Constant") {
    
    # Loop through this to fill them in
    for(y in 1:nrow(Fish_selex_at_age)) {
      
      Fish_selex_at_age[y,,] <<- Fish_Selex
      
    } # end y for time-invariant loop

  } # if statement for constant selectivity
  
    

# 2DAR1 Selex for the Fishery (Preliminary) -------------------------------------------------------------------
  
  if(Fish_Time == "2DAR1") {
    
    # Get multivariate random draws
    for(sim in 1:n_sims) {
      
      # Create covariance matrix to feed into rmvnorm
      
      # Sigma_Fish^2 * Correlation (rho_age_fish) = the covariance, diagonals get populated by the
      # variance, and the off diagonals get populated by the covariance
      Cov_Age_Year <- Sigma_Fish^2 * rho_age_fish^as.matrix(dist(min(ages):max(ages), diag = TRUE, upper = TRUE))
      
      # Mean vector of draws (mean of 0) - repeated by max ages - 1
      mean_0_vec <- rep(0,(max(ages)-1))
      
      for(y in 1:n_years) {
        
        if(y == 1) { # put deviations in the first row - across ages if year = 1
          
          # Put deviations by age into the selex dev array for the first year
          Selex_dev[y,,sim] <- mvtnorm::rmvnorm( n=1, mean=mean_0_vec, sigma=Cov_Age_Year )[1,]
          
        } else{ # if year != 1
          
          # Now, derive our correaltion and variance across time, generated by deviations by ages
          # Rho time fish * Selex dev specifies how much they're correlated by time 
          # sqrt(1-rho_time_fish^2) species the degree of nonassociation. We then multiply
          # that by our next set of multivariate draws by age
          Selex_dev[y,,sim] <- rho_time_fish * Selex_dev[y-1,,sim] + sqrt(1-rho_time_fish^2) * 
            mvtnorm::rmvnorm( n=1, mean=mean_0_vec, sigma= Cov_Age_Year )[1,]
        } # end 2DAR1 error draws
        
        # Mutliply these multivariate draws by the selectivity at age - scale to a max of 1
        Fish_selex_at_age[y,,sim] <- Fish_Selex * exp(Selex_dev[y,,sim]) / max(Fish_Selex * exp(Selex_dev[y,,sim]))
        
      } # end year loop
      
    } # end sim loop
    
  } # end 2DAR1


# Survey Selex------------------------------------------------------------------
  
  # Survey is always assumed time-invariant and asymptotic
  
    # Base functional form here
    Surv_Selex <- 1 / (1 + (exp(-(ages - a50_surv)/k_surv)) )
    
      # Loop through this to fill them in
      for(y in 1:nrow(Fish_selex_at_age)) {
        
        Surv_selex_at_age[y,,] <- Surv_Selex
        
      } # end y for time-invariant loop
    
    
    # Output fishery selectivity into environment
    Fish_selex_at_age <<- Fish_selex_at_age
    
    # Output values for Survey Selex
    Surv_selex_at_age <<- Surv_selex_at_age
    
    print(paste("Fishery Selectivity is specified as:", Fish_Funct_Form, "and", Fish_Time))
    print(paste("Survey Selectivity is specified as:", Surv_Funct_Form))
    
  
} # end function



